replicaCount: 2

image:
  repository: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/mern-backend-helloservice
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 3000

containerPort: 3000