apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: backend
          image: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/mern-backend-helloservice:latest
          ports:
            - containerPort: 3000
